name: Build container
run-name: Build container
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    if: ${{ github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/ci-cd' }}
    # TODO: change branch to "main"
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract image meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/flags/data-harvester
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}